#!/usr/bin/env bash
# Compiles scripts/lib/i18n/fr.tsv ("English<TAB>French", one sentence per line) into scripts/lib/i18n/fr.sh:
# a _t_fr function made of a single case, fast even in bash 3.2 (no associative arrays).
set -euo pipefail
cd "$(dirname "$0")/.."
python3 - <<'PY'
import sys
src = "scripts/lib/i18n/fr.tsv"; out = "scripts/lib/i18n/fr.sh"
q = lambda s: "'" + s.replace("'", "'\\''") + "'"
seen = {}; lines = []
for n, raw in enumerate(open(src, encoding="utf-8"), 1):
    raw = raw.rstrip("\n")
    if not raw or raw.startswith("#"): continue
    if "\t" not in raw: sys.exit(f"{src}:{n}: missing tab")
    en, fr = raw.split("\t", 1)
    if en in seen: sys.exit(f"{src}:{n}: duplicate sentence (already line {seen[en]})")
    seen[en] = n; lines.append(f"    {q(en)}) _T={q(fr)} ;;")
open(out, "w", encoding="utf-8").write(
  "#!/usr/bin/env bash\n# Generated by tools/i18n-build.sh from fr.tsv: do not edit by hand.\n"
  "# shellcheck disable=SC2034\n_t_fr() {\n  _T=\"\"\n  case \"$1\" in\n" + "\n".join(lines) + "\n  esac\n}\n")
print(f"{len(lines)} sentences → {out}")
PY
